apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pmt
  template:
    metadata:
      labels:
        app: pmt
    spec:
      containers:
        - name: pmt
          image: pmt-api:local
          imagePullPolicy: Never   # use the locally built image, don't try to pull
          ports:
            - containerPort: 8080
            - containerPort: 9090
          env:
            - name: DB_HOST
              value: db # meta name
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: pmt
spec:
  selector:
    app: pmt
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 9090
      targetPort: 9090
